Debate scheduler
julianmichael/debate pull request #79
Opened 2023-01-21 20:42 UTC by smithjessk

Draft :) 

Some evidence that this works:

<img width="798" alt="image" src="https://user-images.githubusercontent.com/5957838/213886377-a11b06f6-75b9-4cbd-b4ef-e2a42e04fc6e.png">

2023-02-02 22:47 UTC, julianmichael requested changes
Finally got around to this. Looks good overall, let me know if you have any followup questions.

2023-02-02 22:47 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +  def getNTimesDebated(assignments: Vector[DebateAssignment]): Map[String, Int] = assignments
A more succinct and (IMO) clear way of doing this:
```scala
assignments.foldMap { assignment =>
  val debaters = a.dishonestDebaters + assignment.honestDebater
  debaters.view.map(_ -> 1).toMap
}
```
May not be obvious until you remember the monoid for `Map` combines the values according to their monoid, which for `Int` is addition. So it's like summing a list of python `Counter`s here. I admit it's a tiny bit less legible if that's not muscle memory but I use it _so_ much I think it's worth adopting as a common pattern.

And if you don't like it, I have a `counts` utility which does it for you:
```scala
import jjm.implicits._
assignments.flatMap { assignment =>
  assignment.dishonestDebaters + assignment.honestDebater
}.counts
```

2023-02-02 22:47 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +  def debaterCost(assignments: Vector[DebateAssignment]): Double = {
I have some utilities for this in `jjm.metrics`. You can implement this function as:
```scala
import jjm.metrics.Numbers
def debaterCost(assignments: Vector[DebateAssignment]): Double = {
  Numbers(getNTimesDebated(assignments).values.toVector).stats.mean
}
```

2023-02-02 22:47 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +    allPossibleQuestionAssignments.toVector.combinations(numQuestions).toVector
Seems fine for now, as repeating assignments in a single round of scheduling seems very unlikely to be something we want, but technically we might either
1. be in the situation where an assignment needs to repeat in order to balance things out (I think this is ok if it happens — after all, they won't _know_ it's happening, necessarily, or if they do, then it's probably intentional e.g. with load constraints), or
2. we're scheduling more debates than there are possible assignments (if we want to use for longer-term scheduling)

So could be worth just noting the shortcomings in a comment here for later.

2023-02-02 22:47 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +  def randomIndexOverProbabilities(probabilities: Vector[Double]): Int = {
I think you can just call this `sample`?

2023-02-02 22:47 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +  def randomIndexOverProbabilities(probabilities: Vector[Double]): Int = {
Also how about making the `Random` a parameter with `scala.util.Random` as its default value?

2023-02-02 22:47 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +    correspondingCosts = correspondingCosts.map { cost =>
Factor out z-scoring into a separate function?

2023-02-02 22:47 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +    val allAssignmentsThatMeetConstraints: Vector[Vector[DebateAssignment]] = allAssignments
Probably can just chain the `filter` onto the previous line so we only have one assignment

2023-02-02 22:47 UTC, julianmichael commented on debate/test/src/SchedulerTests.scala
> +      // TODO type system for encoding length
? — if you mean using type-level nats or literal types, it's probably not worth the trouble. On the other hand, testing this more thoroughly with ScalaCheck is an option, but I'm not sure it's worth the effort either right now.

2023-02-02 22:47 UTC, julianmichael commented on debate/test/src/SchedulerTests.scala
> +  // TODO probably export this to the debate rules object
Any reason not to just use the existing `DebateRules.default`?

2023-02-02 22:47 UTC, julianmichael commented on debate/test/src/SchedulerTests.scala
> +      history = history :+ testDebateOfAssignment(newAssignment.head)
Costs may indeed go up over time and it be fine. What we're doing is we're trying to minimize the cost _conditional_ on adding `n` more assignments. So even if the cost goes up, our goal is that it be low relative to alternative choices we could have made. Plausible for us that it shouldn't go up, because intuitively, stdev-like values shouldn't necessarily grow as the total `N` increases, but not necessarily a sign of a bug in the overall algorithm.

2023-02-07 16:49 UTC, smithjessk commented on debate/src/DebateState.scala
> +  def honestDebaterAssignment: Option[String] = setup.roles.get(Debater(setup.correctAnswerIndex))
6f4ba70 ty!

2023-02-07 16:54 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    for (debater <- debaters.keys) {
nice, ba541d6217dcd9f9c02c429a175e3e72d68561dd, ty! :)

2023-02-07 16:54 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +      if (constraint.max.isDefined && constraint.max.get < nParticipanting) {
Nice! ba541d6217dcd9f9c02c429a175e3e72d68561dd ty :)

2023-02-07 16:57 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    assignment: Vector[DebateAssignment],
22b544159bd03a7916aedd61659e0bc0cccc6acb ty!

2023-02-07 16:57 UTC, smithjessk commented on debate/test/src/SchedulerTests.scala
> +      // TODO type system for encoding length
Ack!

2023-02-07 16:59 UTC, smithjessk commented on debate/test/src/SchedulerTests.scala
> +  // TODO probably export this to the debate rules object
just that i forgot it :) d639972cee9e6e3409a139191e1945236ef6c2ea ty

2023-02-07 17:01 UTC, smithjessk commented on debate/test/src/SchedulerTests.scala
> +      history = history :+ testDebateOfAssignment(newAssignment.head)
hmm, yeah- i'm not sure why the costs are going up over time. i'm going to opt for the strategy of 'keep going with all the other cost functions and confirm that the end result looks reasonable'

2023-02-07 17:04 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +  def getNTimesDebated(assignments: Vector[DebateAssignment]): Map[String, Int] = assignments
597329530cb5041cd6ddc3dfe05f4bc544bf1c81, nice! i tried your first option but got a compilation error that `assignments` didn't have `foldMap`. didn't wanna investigate since option 2 seemed quite nice too :P

2023-02-07 17:06 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +  def getNTimesDebated(assignments: Vector[DebateAssignment]): Map[String, Int] = assignments
also in a subsequent commit i moved the import to the top of the file!

2023-02-07 17:07 UTC, smithjessk commented on debate/test/src/SchedulerTests.scala
> +      history = history :+ testDebateOfAssignment(newAssignment.head)
also fwiw the costs seem to plateau out: e.g. they go from 0 -> 15 pretty fast and then grow much more slowly. seems like the right behavior?

2023-02-07 17:09 UTC, smithjessk commented on debate/test/src/SchedulerTests.scala
> +      history = history :+ testDebateOfAssignment(newAssignment.head)
(although maybe that's because the later assignments are just much slower so it _subjectively_ seems like the costs are growing slower)

2023-02-07 17:09 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    val allAssignmentsThatMeetConstraints: Vector[Vector[DebateAssignment]] = allAssignments
04bed36

2023-02-07 17:13 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    correspondingCosts = correspondingCosts.map { cost =>
be969aa97213dd23de6e8568498d55244dd37c9f

2023-02-07 17:15 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +  // TODO do we need to obey the constraints on the number of judges and dishonest debaters? (present in the debates in the history)
lol im not sure; taking it out :)

2023-02-07 17:15 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +  // TODO do we need to obey the constraints on the number of judges and dishonest debaters? (present in the debates in the history)
i thought about it for a bit and can't think of an obvious reasonable interpretation. i think i was probably just figuring things out and asking half-baked questions to myself

2023-02-07 17:22 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +  def debaterCost(assignments: Vector[DebateAssignment]): Double = {
I think you meant `.stddev`, not `.mean`. If so, 36a8971! And this fixes the costs going up continuously :) 

<img width="863" alt="image" src="https://user-images.githubusercontent.com/5957838/217318034-57e5a490-3108-4782-b99d-5510c100503e.png">

2023-02-07 17:22 UTC, smithjessk commented on debate/test/src/SchedulerTests.scala
> +      history = history :+ testDebateOfAssignment(newAssignment.head)
whoops! https://github.com/julianmichael/debate/pull/79#discussion_r1098975011

2023-02-07 17:33 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    allPossibleQuestionAssignments.toVector.combinations(numQuestions).toVector
68a47cb

2023-02-07 17:36 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +  def randomIndexOverProbabilities(probabilities: Vector[Double]): Int = {
cc315fd

2023-02-07 20:27 UTC, julianmichael requested changes
Looking good! I suggested some more changes inline, including a few that I think affect the functionality (where we want `foldMap` instead of `flatMap` in order to aggregate counts properly).

2023-02-07 20:27 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +    val fractionsHonest: Map[String, Double] = timesHonest.map { case (debater, nHonest) =>
This excludes people who have only ever been dishonest. This is a place where `.align` and `Ior` (inclusive or) from cats could come in use:
```scala
import cats.implicits._
timesHonest.align(timesDishonest).values.view.map(
  _.fold(
    _ => 1.0, // honest only
    _ => 0.0, // dishonest only
    (nHonest, nDishonest) => nHonest.toDouble / (nHonest + nDishonest)
  )
)
```
This expands to basically:
```scala
timesHonest.align(timesDishonest).values.view.map(valIor =>
  valIor match {
    case Ior.Left(nHonest) => 1.0
    case Ior.Right(nDishonest) => 0.0
    case Ior.Both(nHonest, nDishonest) => nHonest.toDouble / (nHonest + nDishonest)
  }
)
```
Alternatively, you could also do
```scala
val debaters = timesHonest.keySet ++ timesDishonest.keySet
val fractionsHonest = debaters.view.map { debater =>
  val nHonest = timesHonest.getOrElse(debater, 0)
  val nDishonest = timesDishonest.getOrElse(debater, 0)
  debater -> (nHonest.toDouble / (nHonest + nDishonest)
}.toMap
```
... which... actually is probably the best option haha. But I already wrote all of these, so there you go 🤠

2023-02-07 20:27 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +    cost = cost + debaterCost(assignments)
I think `+=` will work here? I use vars so rarely that I can't even remember lol. Alternatively you could just put them all per-line in a `List` and take the `.sum` at the end.

2023-02-07 20:27 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +        .map { cost =>
I think you can just `.map(math.exp)`

2023-02-07 20:27 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +        .map { cost =>
also you can reuse `val expCosts = correspondingCosts.map(math.exp)` for the probabilities as well

2023-02-07 20:27 UTC, julianmichael commented on debate/test/src/SchedulerTests.scala
> +      answers = Vector.empty[String],
This is technically invalid — `answers` must be nonempty and `correctAnswerIndex` must be a valid index into it. Later I should add some assertions & maybe make the type `NonEmptyVector` — don't worry about it now.

2023-02-07 20:27 UTC, julianmichael commented on debate/test/src/SchedulerTests.scala
> +      answers = Vector.empty[String],
(fix: just put a couple dummy answers)

2023-02-07 20:27 UTC, julianmichael commented on debate/test/src/SchedulerTests.scala
> +      history = history :+ testDebateOfAssignment(newAssignment.head)
Ah thanks for the correction, I meant the standard deviation yeah.

If our costs are all standard deviations, I would expect them to start higher and then pretty quickly go down and oscillate a tiny bit around a plateau.

2023-02-07 23:43 UTC, smithjessk commented on debate/test/src/SchedulerTests.scala
> +      history = history :+ testDebateOfAssignment(newAssignment.head)
Word. For standard-deviation based costs _only_ for the number of debates per debater:

```
0.0, 0.0, 0.816496580927726, 0.4714045207910317, 0.4714045207910317, 0.0, 0.4714045207910317, 
0.4714045207910317, 0.0, 0.4714045207910317, 0.4714045207910317, 0.816496580927726, 0.4714045207910317, 
0.4714045207910317, 0.816496580927726, 0.4714045207910317, 0.4714045207910317, 0.0, 0.4714045207910317, 
0.4714045207910317, 0.0, 0.4714045207910317, 0.4714045207910317, 0.0, 0.4714045207910317
```

So not really the behavior you're describing, I think. OTOH I think this might be because the # of debaters is small. It solves the problem pretty exactly:

```
(n times debated,Map(debater3 -> 16, debater2 -> 17, debater1 -> 17))
```

If you'd like, I can do a larger study with `n > 10` debaters.

2023-02-08 03:03 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    var randomKey = scala.util.Random.nextString(10)
in order to account for the fact that the new assignment is a new story. this was definitely a quick and dirty way to write this :P 

aka, to make it work with this data structure, which I wrote this function around:

```scala
val storyToPersonToJudgeCount: Map[String, Map[String, Int]]
```

2023-02-08 03:28 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +  /** Don't use this directly, use [DebateAssignment.apply] instead */
4d5ae0d ty! :)

2023-02-08 03:28 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    def apply(
4d5ae0d ty! :)

2023-02-08 03:29 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +  def storiesRead(history: Vector[Debate], newAssignments: Vector[DebateAssignment]): Double = {
4d5ae0d ty! :)

2023-02-08 03:29 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    val fractionsHonest: Map[String, Double] = timesHonest.map { case (debater, nHonest) =>
4d5ae0d ty! :)

2023-02-08 03:29 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    cost = cost + debaterCost(assignments)
4d5ae0d ty! :)

2023-02-08 03:29 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +        .map { cost =>
4d5ae0d ty! :)

2023-02-08 03:49 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +        .flatMap { case (judge, debaters) =>
I was having some trouble with the compiler. `foldMap` doesn't exist on `Map`, but `foldMapK` does, but that didn't seem like exactly what we wanted since we depend on the keys to compute these new maps.

How does this look? Might be time to upgrade my Scala knowledge :O :) 

```scala
val judgedPerDebater: Map[(String, String), Int] = judgeToDebaters
    .toSeq
    .foldMap { case (judge, debaters) =>
      debaters
        .toSeq
        .foldMap { debater =>
          Map((judge, debater) -> 1)
        }
 }
```

2023-02-08 03:52 UTC, smithjessk commented on debate/test/src/SchedulerTests.scala
> +      answers = Vector.empty[String],
ty! 6b3190c :)

2023-02-08 03:52 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +        .flatMap { case (judge, debaters) =>
(but addressed in 6b3190c)

2023-02-08 03:52 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +        .flatMap { assignment =>
6b3190c thanks!

2023-02-08 03:55 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    val adversarialPairs: Map[Set[String], Int] =
6b3190c

thanks :)

2023-02-08 03:55 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    val judgingInHistory: Map[String, Map[String, Int]] =
6b3190c thanks :)

2023-02-08 16:40 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +    def apply(
Either should put the error case in the `Left` — see [here](https://typelevel.org/cats/datatypes/either.html)

2023-02-08 16:43 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +    var randomKey = scala.util.Random.nextString(10)
Ohh I see. Why don't we just take the new story key as a parameter at the beginning of everything? And actually, I think everything should still work even if the story isn't new — right?

2023-02-08 16:46 UTC, julianmichael commented on debate/test/src/SchedulerTests.scala
> +      history = history :+ testDebateOfAssignment(newAssignment.head)
Yeah I think the number of debaters is so small that these are our kind of small oscillations. No worries about a larger study, a more e2e test later should do the job

2023-02-09 15:54 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +    var randomKey = scala.util.Random.nextString(10)
1- taking the new story key as a parameter seems fine! 
2- i don't think everything will work as-is if the story isn't new. Consider the following, which assumes that the requested assignment is for a new story:

```scala
  def storiesReadCost(history: Vector[Debate], newAssignments: Vector[DebateAssignment]): Double = {
    val debaterStoriesRead: Map[String, Set[String]] = history.foldMap { debate =>
      DebateAssignment
        .ofDebate(debate)
        .foldMap { assignment =>
          (assignment.dishonestDebaters + assignment.honestDebater)
            .view
            .map(debater => debater -> Set(debate.setup.sourceMaterial.title))
            .toMap
        }
    }

    val countsInNewAssignment: Map[String, Int] = newAssignments.foldMap { assignment =>
      (assignment.dishonestDebaters + assignment.honestDebater)
        .view
        .map(debater => debater -> 1)
        .toMap
    }
```

That being said, it seems easy to change this function and the other ones to work both in the case where the story is new and the case where it's not.

2023-02-09 16:18 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +    var randomKey = scala.util.Random.nextString(10)
Ok! I'm happy to leave that to later

2023-02-09 16:19 UTC, julianmichael approved these changes
LGTM! Thanks!!

2023-02-13 02:17 UTC, julianmichael requested changes
Just one quick cleanup fix and then feel free to merge!

2023-02-13 02:17 UTC, julianmichael commented on debate/src/DebateScheduler.scala
> +      debaterStoriesRead
Here you can just do
```scala
debaterStoriesRead |+| mapFromNewAssignments
```
where `|+|` is the syntax for the `Monoid#combine` function, here from `Monoid[Map[String, Set[String]]]`

2023-02-13 04:57 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +      debaterStoriesRead
FWIW, when testing this a bit more, I noticed that assigning 25 debates would sometimes result in one user being assigned way less than the others. E.g.:

```
(n times debated,Map(debater3 -> 22, debater2 -> 21, debater1 -> 7))
(n times debated,Map(debater3 -> 25, debater2 -> 25))
```

This wasn't the norm, but it did happen sometimes!

The behavior basically disappeared when I changed the for loop [1] to stop at `100` instead of `25`:

```
(base) jesssmith@Jesss-Air debate % for i in $(seq 20); do mill debate.jvm.test 2&>/dev/null | rg 'n times debated'; done
(n times debated,Map(debater3 -> 66, debater2 -> 67, debater1 -> 67))
(n times debated,Map(debater3 -> 67, debater2 -> 65, debater1 -> 68))
(n times debated,Map(debater3 -> 67, debater2 -> 67, debater1 -> 66))
(n times debated,Map(debater3 -> 66, debater2 -> 67, debater1 -> 67))
(n times debated,Map(debater3 -> 67, debater2 -> 66, debater1 -> 67))
(n times debated,Map(debater3 -> 67, debater2 -> 66, debater1 -> 67))
(n times debated,Map(debater3 -> 66, debater2 -> 67, debater1 -> 67))
(n times debated,Map(debater3 -> 67, debater2 -> 67, debater1 -> 66))
(n times debated,Map(debater3 -> 67, debater2 -> 67, debater1 -> 66))
(n times debated,Map(debater3 -> 66, debater2 -> 67, debater1 -> 67))
(n times debated,Map(debater3 -> 66, debater2 -> 67, debater1 -> 67))
(n times debated,Map(debater3 -> 67, debater2 -> 66, debater1 -> 67))
(n times debated,Map(debater3 -> 66, debater2 -> 67, debater1 -> 67))
(n times debated,Map(debater3 -> 67, debater2 -> 66, debater1 -> 67))
(n times debated,Map(debater3 -> 66, debater2 -> 67, debater1 -> 67))
(n times debated,Map(debater3 -> 67, debater2 -> 67, debater1 -> 66))
(n times debated,Map(debater3 -> 66, debater2 -> 68, debater1 -> 66))
(n times debated,Map(debater3 -> 66, debater2 -> 67, debater1 -> 67))
(n times debated,Map(debater3 -> 67, debater2 -> 67, debater1 -> 66))
(n times debated,Map(debater3 -> 66, debater2 -> 67, debater1 -> 67))
```

[1]: Inside   `test("debater-only costs go down over time")` in `SchedulerTests.scala`.

2023-02-13 04:57 UTC, smithjessk commented on debate/src/DebateScheduler.scala
> +      debaterStoriesRead
(Anyway, addressed in 5ccd357b834ed48502c794d89ddb7dcaa830c1ab :) ty!)

2023-03-01 23:50 UTC, julianmichael approved these changes

2023-03-01 23:50 UTC, merged